Repository Android-Team-1RM/SparTube, pull requests merged in 2023-10, with the labels that each got.

#58 [FEAT] : ⚙️, [UI] : 🎨​ SearchFragment, SearchAdapter
  app/src/main/java/com/example/naebaecamteam1rm_spartube/data/TubeDataModel.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/searchpage/SearchAdapter.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/searchpage/SearchFragment.kt
  app/src/main/res/layout/item_fragment_search.xml
Labels: Feat, UI

#61 [FEAT] : ⚙️ 채널 썸네일이미지 구현
  .idea/misc.xml
  app/src/main/java/com/example/naebaecamteam1rm_spartube/data/ChannelDTO.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/data/TubeDataModel.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/data/VideoDTO.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/data/VideoService.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/homepage/HomeFragment.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/mypage/MyPageAdapter.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/mypage/MyPageFragment.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/mypage/MyPageModel.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/searchpage/SearchAdapter.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/videodetailpage/VideoDetailPageActivity.kt
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/item_my_page_recyclerview.xml
Labels: Feat

#62 [UI] : 🎨, [FEAT] : ⚙️
  app/src/main/java/com/example/naebaecamteam1rm_spartube/data/VideoDTO.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/data/VideoService.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/homepage/HomeAdapter.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/homepage/HomeFragment.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/videodetailpage/VideoDetailPageActivity.kt
  app/src/main/res/drawable/video_detail_page_btn_shape_like.xml
  app/src/main/res/layout/activity_video_detail_page.xml
Labels: Feat, UI

#64 [FEAT] : ⚙️ SearchFragment 채널썸네일
  app/src/main/java/com/example/naebaecamteam1rm_spartube/searchpage/SearchAdapter.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/searchpage/SearchFragment.kt
  app/src/main/res/layout/item_fragment_search.xml
Labels: Feat

#69 [UI] : 🎨 썸네일 이미지 CardView 사용, 라운딩 처리
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/naebaecamteam1rm_spartube/mypage/MyPageAdapter.kt
  app/src/main/res/layout/item_my_page_recyclerview.xml
Labels: UI

#70 [FIX] : 🐛 viewModel url 에 videoId들어가던 내용 수정
  app/src/main/java/com/example/naebaecamteam1rm_spartube/videodetailpage/VideoDetailPageActivity.kt
Labels: bug

#71 [FEAT] : ⚙️ SearchFragment infinite scroll
  .idea/misc.xml
  app/src/main/java/com/example/naebaecamteam1rm_spartube/searchpage/SearchAdapter.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/searchpage/SearchFragment.kt
  app/src/main/res/layout/item_fragment_search.xml
  build.gradle
Labels: Feat

#73 [COMPLETION] : 🎉인피니티스크롤 적용
  app/src/main/java/com/example/naebaecamteam1rm_spartube/data/ChannelDTO.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/data/VideoService.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/homepage/HomeFragment.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/mypage/MyPageAdapter.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/mypage/MyPageFragment.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/mypage/MyPageViewModel.kt
  app/src/main/res/layout/fragment_my_page.xml
Labels: Feat

#75 Playlist 5
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/src/main/java/com/example/naebaecamteam1rm_spartube/main/ViewPagerAdapter.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/playlistpage/PlayListAdapter.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/playlistpage/PlayListFragment.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/playlistpage/PlayListModel.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/playlistpage/PlayListViewModel.kt
  app/src/main/res/layout/alertdialog_edittext.xml
  app/src/main/res/layout/fragment_playlist.xml
  app/src/main/res/layout/item_playlist.xml
Labels: Feat

#77 Fix/mypage
  app/src/main/java/com/example/naebaecamteam1rm_spartube/Utils.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/homepage/HomeAdapter.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/homepage/HomeFragment.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/playlistpage/PlayListFragment.kt
Labels: bug

#78 임시 UI 수정
  app/src/main/java/com/example/naebaecamteam1rm_spartube/playlistpage/PlayListAdapter.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/playlistpage/PlayListFragment.kt
  app/src/main/res/drawable/play_list_page_ic_add.xml
  app/src/main/res/layout/activity_video_detail_page.xml
  app/src/main/res/layout/alertdialog_edittext.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_playlist.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/item_fragment_search.xml
  app/src/main/res/layout/item_homefragment_shorts.xml
  app/src/main/res/layout/item_my_page_recyclerview.xml
  app/src/main/res/layout/item_playlist.xml
  app/src/main/res/layout/item_recyclerview.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: Feat, UI

#80 임시 PR
  app/src/main/java/com/example/naebaecamteam1rm_spartube/Utils.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/homepage/HomeAdapter.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/homepage/HomeCannelAdapter.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/homepage/HomeFragment.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/homepage/HomeShortsAdapter.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/main/MainActivity.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/main/ViewPagerAdapter.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/mypage/MyPageFragment.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/mypage/MyPageViewModel.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/playlistpage/PlayListAdapter.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/playlistpage/PlayListFragment.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/searchpage/SearchAdapter.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/searchpage/SearchFragment.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/videodetailpage/VideoDetailPageActivity.kt
  app/src/main/res/layout/activity_video_detail_page.xml
  app/src/main/res/layout/item_fragment_search.xml
  app/src/main/res/layout/item_loading_vertical.xml
  app/src/main/res/layout/item_my_page_recyclerview.xml
Labels: bug

#84 [FEAT] : ⚙️ SearchFragment infinite scroll
  app/src/main/java/com/example/naebaecamteam1rm_spartube/searchpage/SearchFragment.kt
Labels: Feat

#86 최종 PR
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/naebaecamteam1rm_spartube/Utils.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/homepage/HomeAdapter.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/homepage/HomeCannelAdapter.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/main/MainActivity.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/main/ViewPagerAdapter.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/mypage/MyPageFragment.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/mypage/MyPageViewModel.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/playlistpage/PlayListFragment.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/searchpage/SearchAdapter.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/searchpage/SearchFragment.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/videodetailpage/VideoDetailPageActivity.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_video_detail_page.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/item_fragment_search.xml
  app/src/main/res/layout/item_homefragment_shorts.xml
  app/src/main/res/layout/item_loading_vertical.xml
  app/src/main/res/layout/item_my_page_recyclerview.xml
  app/src/main/res/layout/item_recyclerview.xml
Labels: Feat, UI
