Repository Android-Team-1RM/SparTube, pull requests merged in 2023-09, with the labels that each got.

#4 UI/mypage
  .idea/gradle.xml
  .idea/misc.xml
  app/build.gradle
  app/src/main/res/drawable/mypage_img_profile.jpg
  app/src/main/res/drawable/mypage_img_profile_background.png
  app/src/main/res/layout/my_page_fragment.xml
Labels: UI

#6 [UI] : 🎨 fragment_search.xml UI
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/java/com/example/naebaecamteam1rm_spartube/SearchFragment.kt
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/values/strings.xml
Labels: UI

#8 Playlist
  app/src/main/java/com/example/naebaecamteam1rm_spartube/PlaylistFragment.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/ViewPagerAdapter.kt
Labels: Feat

#10 [FEAT] : ⚙️ MypageFragment 생성 및 어뎁터 연결
  app/src/main/java/com/example/naebaecamteam1rm_spartube/MyPageFragment.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/ViewPagerAdapter.kt
Labels: Feat

#13 [UI] : 🎨VideoDetailPageActivity 설정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/naebaecamteam1rm_spartube/MainActivity.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/VideoDetailPageActivity.kt
  app/src/main/res/anim/activity_video_detail_page_slide_up.xml
  app/src/main/res/drawable/video_detail_page_ic_btn_down.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_video_detail_page.xml
  app/src/main/res/values/colors.xml
Labels: UI

#14 [FEAT] : ⚙️ PlaylistFragment
  app/src/main/java/com/example/naebaecamteam1rm_spartube/PlaylistFragment.kt
  app/src/main/res/layout/fragment_playlist.xml
Labels: Feat

#16 [FEAT] : ⚙️ SearchFragment 추천 검색 구현, [UI] : 🎨 fragment_search.xml 추가
  app/src/main/java/com/example/naebaecamteam1rm_spartube/SearchFragment.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/ViewPagerAdapter.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/search/ListOfWord.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/search/SearchFragment.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/search/SearchViewModel.kt
  app/src/main/res/drawable/search_img_refresh.png
  app/src/main/res/drawable/search_random_btn.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: Feat, UI

#18 [FEAT] : ⚙️ Youtube Api 연결
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/naebaecamteam1rm_spartube/MyPageFragment.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/data/TestData.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/data/TubeDataModel.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/data/VideoDTO.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/data/VideoService.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/home/HomeAdapter.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/home/HomeFragment.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/home/YoutubeActivity.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/home/YoutubeAdapter.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/search/SearchFragment.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/item_recyclerview.xml
Labels: Feat

#19 [FIX] : 🔧 RetorfitInstance 파일 누락 추가
  app/src/main/java/com/example/naebaecamteam1rm_spartube/data/RetrofitInstance.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/home/HomeFragment.kt
Labels: bug

#21 [FEAT] : ⚙️ Mypage 리사이클러뷰 생성
  app/src/main/java/com/example/naebaecamteam1rm_spartube/mypage/MyPageAdapter.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/mypage/MyPageFragment.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/mypage/MyPageModel.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/mypage/MyPageViewModel.kt
Labels: Feat

#22 [FEAT] : ⚙️ Home 클릭 이벤트 추가
  .idea/misc.xml
  app/build.gradle
  app/src/main/java/com/example/naebaecamteam1rm_spartube/MainActivity.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/ViewPagerAdapter.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/data/RetrofitInstance.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/data/TubeDataModel.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/data/VideoDTO.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/data/VideoData.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/home/HomeAdapter.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/home/HomeFragment.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/home/YoutubeActivity.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/home/YoutubeAdapter.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_recyclerview.xml
Labels: Feat, UI

#25 [UI] : 🎨 activity_video_detail_page 디자인 수정, [FEAT] : ⚙️ VideoDetailPageActivity 기능 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/naebaecamteam1rm_spartube/VideoDetailPageActivity.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/home/HomeAdapter.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/home/HomeFragment.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/main/MainActivity.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/main/ViewPagerAdapter.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/mypage/MyPageFragment.kt
  app/src/main/res/drawable/video_detail_page_btn_shape.xml
  app/src/main/res/drawable/video_detail_page_img_base.jpg
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_video_detail_page.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: Feat, UI

#26 [FEAT] : ⚙️VideoDetailPageActivity, MyPageAdapter, MyPageFragment
  app/src/main/java/com/example/naebaecamteam1rm_spartube/VideoDetailPageActivity.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/mypage/MyPageAdapter.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/mypage/MyPageFragment.kt
  app/src/main/res/values/colors.xml
Labels: Feat

#29 [FEAT] : ⚙️ Mypage랑 Detail 페이지 연동
  app/src/main/java/com/example/naebaecamteam1rm_spartube/VideoDetailPageActivity.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/home/HomeFragment.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/main/MainActivity.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/main/ViewPagerAdapter.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/mypage/MyPageAdapter.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/mypage/MyPageFragment.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/mypage/MyPageModel.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/mypage/MyPageViewModel.kt
Labels: Feat

#34 [FEAT] : ⚙️ SearchFragment 버튼 검색기능 구현
  app/src/main/java/com/example/naebaecamteam1rm_spartube/search/SearchFragment.kt
Labels: Feat

#37 [FIX] : 🐛 좋아요 관련 데이터 흐름 개선, 중복방지
  app/src/main/java/com/example/naebaecamteam1rm_spartube/data/TubeDataModel.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/homepage/HomeAdapter.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/homepage/HomeFragment.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/main/MainActivity.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/main/ViewPagerAdapter.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/mypage/MyPageAdapter.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/mypage/MyPageFragment.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/mypage/MyPageModel.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/mypage/MyPageViewModel.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/videodetailpage/VideoDetailPageActivity.kt
  app/src/main/res/layout/item_my_page_recyclerview.xml
Labels: bug

#39 [FIX] : 🔧 Constants 수정
  app/src/main/java/com/example/naebaecamteam1rm_spartube/homepage/HomeFragment.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/searchpage/SearchFragment.kt
Labels: Feat

#41 [FEAT] : ⚙️ SharedPreferences 적용
  app/src/main/java/com/example/naebaecamteam1rm_spartube/Utils.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/homepage/HomeFragment.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/mypage/MyPageFragment.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/mypage/MyPageViewModel.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/searchpage/SearchFragment.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/videodetailpage/VideoDetailPageActivity.kt
  app/src/main/res/drawable/img_my_page_profile_background.jpg
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/item_my_page_recyclerview.xml
Labels: Feat

#47 [FIX] : 🔧 VideoID 데이터 값 구현
  app/src/main/java/com/example/naebaecamteam1rm_spartube/data/TubeDataModel.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/data/VideoDTO.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/homepage/HomeFragment.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/mypage/MyPageModel.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/playlistpage/PlayListModel.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/videodetailpage/VideoDetailPageActivity.kt
  app/src/main/res/layout/fragment_my_page.xml
Labels: bug

#51 [FEAT] : ⚙️ [UI] : 🎨 SearchFragment SearchView 관련
  app/src/main/java/com/example/naebaecamteam1rm_spartube/searchpage/SearchFragment.kt
  app/src/main/res/drawable/baseline_close_24.xml
  app/src/main/res/drawable/baseline_refresh_24.xml
  app/src/main/res/drawable/baseline_search_24.xml
  app/src/main/res/drawable/search_img_refresh.png
  app/src/main/res/drawable/search_random_btn.xml
  app/src/main/res/layout/fragment_search.xml
Labels: Feat, UI

#53 1차 완성 추석 전 PR
  app/src/main/java/com/example/naebaecamteam1rm_spartube/data/VideoDTO.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/data/VideoService.kt
  app/src/main/java/com/example/naebaecamteam1rm_spartube/homepage/HomeFragment.kt
  app/src/main/res/layout/activity_main.xml
Labels: Feat, UI
